spring:
  application:
    name: kotlin-lab

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'


network:
  time-step: 1
  minimum-hold: 45
  stations-csv: src/main/resources/network/stations.csv
  transporters:
    ferries:
      - transport-id: 1
        capacity: 200
        weight: 20000
        top-speed: 15
        power: 5000
      - transport-id: 7
        capacity: 200
        weight: 20000
        top-speed: 7
        power: 1000
    cable-cars:
      - transport-id: 2
        capacity: 20
        weight: 100
        top-speed: 5
        power: 100
    trains:
      - transport-id: 3
        capacity: 1000
        weight: 1000
        top-speed: 28
        power: 3800
      - transport-id: 4
        capacity: 1000
        weight: 1500
        top-speed: 20
        power: 2300
      - transport-id: 5
        capacity: 500
        weight: 1000
        top-speed: 15
        power: 1500
      - transport-id: 6
        capacity: 75
        weight: 200
        top-speed: 30
        power: 70
  lines:
    underground:
      - src/main/resources/network/underground/city.yml
      - src/main/resources/network/underground/jubilee.yml
      - src/main/resources/network/underground/victoria.yml
      - src/main/resources/network/underground/circle.yml
      - src/main/resources/network/underground/bakerloo.yml
      - src/main/resources/network/underground/hammersmith.yml
      - src/main/resources/network/underground/metropolitan.yml
      - src/main/resources/network/underground/central.yml
      - src/main/resources/network/underground/district.yml
      - src/main/resources/network/underground/northern.yml
      - src/main/resources/network/underground/piccadilly.yml
    overground:
      - src/main/resources/network/overground/gospel-oak.yml
      - src/main/resources/network/overground/highbury-islington.yml
      - src/main/resources/network/overground/london-euston.yml
      - src/main/resources/network/overground/romford.yml
      - src/main/resources/network/overground/london-liverpool-st.yml
      - src/main/resources/network/overground/stratford.yml
      - src/main/resources/network/overground/elizabeth.yml
    cable:
      - src/main/resources/network/cable/cable.yml
    river:
      - src/main/resources/network/river/river.yml
    dockland:
      - src/main/resources/network/dockland/dlr.yml
    tram:
      - src/main/resources/network/tram/tram.yml
#22 lines